"""job definitions, parameters; rename jobs to job_runs

Revision ID: 16d6f04ba0a4
Revises: 4f05c331e51c
Create Date: 2026-06-17 14:21:15.326214

"""
from alembic import op
import sqlalchemy as sa
import app.security


# revision identifiers, used by Alembic.
revision = '16d6f04ba0a4'
down_revision = '4f05c331e51c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('script_path', sa.String(length=1024), nullable=False),
    sa.Column('schedule', sa.String(length=255), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_definitions_name'), ['name'], unique=True)

    op.create_table('job_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_definition_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', app.security.EncryptedString(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['job_definition_id'], ['job_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_definition_id', 'key', name='uq_job_parameter_key')
    )
    with op.batch_alter_table('job_parameters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_parameters_job_definition_id'), ['job_definition_id'], unique=False)

    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('job_definition_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_definition_id'], ['job_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_runs_job_definition_id'), ['job_definition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_runs_task_id'), ['task_id'], unique=True)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_task_id'))

    op.drop_table('jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_task_id'), ['task_id'], unique=1)

    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_runs_task_id'))
        batch_op.drop_index(batch_op.f('ix_job_runs_job_definition_id'))

    op.drop_table('job_runs')
    with op.batch_alter_table('job_parameters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_parameters_job_definition_id'))

    op.drop_table('job_parameters')
    with op.batch_alter_table('job_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_definitions_name'))

    op.drop_table('job_definitions')
    # ### end Alembic commands ###
