"""add job_run_outputs

Revision ID: de55607a45da
Revises: fe2eb41b4ef7
Create Date: 2026-06-17 16:35:06.809638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de55607a45da'
down_revision = 'fe2eb41b4ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_run_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_run_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_run_id'], ['job_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_run_outputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_run_outputs_job_run_id'), ['job_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_run_outputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_run_outputs_job_run_id'))

    op.drop_table('job_run_outputs')
    # ### end Alembic commands ###
