"""add description to job_definitions

Revision ID: fe2eb41b4ef7
Revises: 16d6f04ba0a4
Create Date: 2026-06-17 16:21:10.053743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2eb41b4ef7'
down_revision = '16d6f04ba0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_definitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_definitions', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
